# Generated by Django 5.2.7 on 2025-10-03 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'verbose_name_plural': 'Conference'},
        ),
        migrations.AlterField(
            model_name='conference',
            name='extra_time',
            field=models.DurationField(default=0, help_text='Дополнительное время в формате ЧЧ:ММ:СС'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conference',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.speaker'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='duration',
            field=models.DurationField(help_text='ЧЧ:ММ:СС или ММ:СС'),
        ),
    ]
