# Generated by Django 5.2.7 on 2025-10-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_conference_options_alter_conference_extra_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
