# Generated by Django 5.2.7 on 2025-10-03 01:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_conference_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
