# Generated by Django 5.2.7 on 2025-10-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_conference_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='duration',
            field=models.PositiveIntegerField(default=5, verbose_name='Длительность (мин)'),
        ),
    ]
