# Generated by Django 5.2.7 on 2025-10-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_speaker_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='extra_time',
            field=models.IntegerField(default=0, help_text='Дополнительное время'),
        ),
    ]
