# Generated by Django 5.2.7 on 2025-10-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_conference_extra_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='extra_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='conference',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
