# Generated by Django 5.2.7 on 2025-10-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_conference_extra_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='remaining_time',
            field=models.IntegerField(default=0),
        ),
    ]
