# Generated by Django 5.2.7 on 2025-10-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_conference_remaining_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='extra_time',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='remaining_time',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='duration',
        ),
        migrations.AddField(
            model_name='speaker',
            name='time_limit',
            field=models.PositiveIntegerField(default=300, verbose_name='Время (сек)'),
        ),
    ]
