# Generated by Django 5.2.7 on 2025-10-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_conference_extra_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='time_limit',
            field=models.IntegerField(default=300, verbose_name='Время (сек)'),
        ),
    ]
