# Generated by Django 5.2.7 on 2025-10-13 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_speaker_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='time_limit',
            field=models.DurationField(default=datetime.timedelta(seconds=300), verbose_name='Время'),
        ),
    ]
