# Generated by Django 5.2.7 on 2025-10-23 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_speaker_time_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='speaker',
            name='time_limit',
            field=models.DurationField(default=datetime.timedelta(seconds=300), verbose_name='Время (ЧЧ:ММ:СС)'),
        ),
    ]
