# Generated by Django 5.2.7 on 2025-11-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_conference_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='show_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='show_topic',
            field=models.BooleanField(default=True),
        ),
    ]
