# Generated by Django 5.2.7 on 2025-12-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_conference_show_name_conference_show_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='topic',
            field=models.CharField(blank=True, max_length=300, verbose_name='Тема выступления'),
        ),
    ]
