# Generated by Django 5.2.7 on 2025-12-15 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_speaker_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='initial_time_limit',
            field=models.DurationField(default=datetime.timedelta(seconds=300), verbose_name='Изначальное время (ЧЧ:ММ:СС)'),
        ),
    ]
