# Generated by Django 5.2.7 on 2026-02-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_speaker_initial_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='singleton_enforcer',
            field=models.BooleanField(default=True, editable=False, unique=True),
        ),
    ]
